class Solution {
public:
    string intToRoman(int num) {
        string s="";
        int n=num;
        int count=0;
        while(n!=0){
            n=n/10;
            count++;
        }
        while(count!=0){
            int i=num/(pow(10,count-1));
            if(count==4){
                if(i==1){
                    s+="M";
                }
                if(i==2){
                    s+="MM";
                }
                if(i==3){
                    s+="MMM";
                }
            }
            if(count==3){
                if(i==1){
                    s+="C";
                }
                if(i==2){
                    s+="CC";
                }
                if(i==3){
                    s+="CCC";
                }
                if(i==4){
                    s+="CD";
                }
                if(i==5){
                    s+="D";
                }
                if(i==6){
                    s+="DC";
                }
                if(i==7){
                    s+="DCC";
                }
                if(i==8){
                    s+="DCCC";
                }
                if(i==9){
                    s+="CM";
                }
            }
            if(count==2){
                if(i==1){
                    s+="X";
                }
                if(i==2){
                    s+="XX";
                }
                if(i==3){
                    s+="XXX";
                }
                if(i==4){
                    s+="XL";
                }
                if(i==5){
                    s+="L";
                }
                if(i==6){
                    s+="LX";
                }
                if(i==7){
                    s+="LXX";
                }
                if(i==8){
                    s+="LXXX";
                }
                if(i==9){
                    s+="XC";
                }
            }
            if(count==1){
                if(i==1){
                    s+="I";
                }
                if(i==2){
                    s+="II";
                }
                if(i==3){
                    s+="III";
                }
                if(i==4){
                    s+="IV";
                }
                if(i==5){
                    s+="V";
                }
                if(i==6){
                    s+="VI";
                }
                if(i==7){
                    s+="VII";
                }
                if(i==8){
                    s+="VIII";
                }
                if(i==9){
                    s+="IX";
                }
            }
            num=num-i*pow(10,count-1);
            if(num==0){
                break;
            }
            count--;
        }
        return s;
    }
};